data:
  path: '/home/lubi/Desktop/K_reports_full.sqlite'
  table_name: 'K_reports_full'
  chunk_table_name: "K_reports_full_sliced_1600"
  limit: 0
  offset: 0


lazy_loading: True
debug: True
number_of_ignorable_tokens_for_masking: 25
pad_token_id: 1
tokenizer: "yiyanghkust/finbert-tone"
use_local_tokenizer: False
local_tokenizer: "/home/lubi/Documents/Projects/BA/src/external/finroberta/data/finroberta_tokenizer.json"
masked_probability: 0.15
context_length: 1500
learning_rate: 0.00003
word_context_length: 1300
context_stride: 512
num_blocks: 12
num_heads: 8
d_model: 512
dropout: 0
reversible: True
projection_option: 0
vocab_size: 30874
train_size:  0.9
use_pretrained_embeddings: False
padding_value: 1
dynamic_masking: False
batch_size: 8
accumulate_steps: 1
mixed_precision: False
large_memory: True
segment_lengths:
  - 250
  - 500
  - 1500

dilation_rates:
  - 1
  - 3
  - 5